[package]
name = "gbars"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "*"
log = "*"

[dev-dependencies]
object = "0.26.2"
env_logger = "*"
